load("@rules_cc//cc:defs.bzl", "cc_binary")

cc_binary(
    name = "hello",
    srcs = ["hello.cpp"],
)

cc_binary(
    name = "cpp11",
    srcs = ["cpp11.cpp"],
)

cc_binary(
    name = "working",
    srcs = ["working.cpp"],
)
